### ISSUE TITLE
Unable to get the result in the readme

### ISSUE THREAD

**Issue by jrabary** [Robert0812/salience_reid#2]
Hi,

I'm trying to run your code with octave. I've able to run it after some little fix ( essentially file system path which is not the same on linux and some indicies for image crop in dense feature computation) but I didn't get the same results as in the readme. After playing with parameter I manage to get 22% accuracy with knn with the following parameters 

```
 par = struct(...
    'dataset',                      'viper', ... % 'viper'
    'baseExp',                      'unsupervised_salience', ...
    'method',                       'salience', ... % 'patchmatch', 'salience' ...
    'TRIAL',                        test_trial, ... % average over 10 trials to obtain stable result
    'gridstep',                     4, ...
    'patchsize',                    12, ...
    'Nr',                           100, ... 
    'sigma1',                       0.9, ...
    'msk_thr',                      0.2, ...
    'norm_data',                    1, ...
    'new_feat',                     1, ...
    'use_mask',                     1, ...
    'use_salience',                 1, ... % set 1 to use knn salience, and set 2 to use ocsvm salience
    'alpha',                        [-1, 0.4, 1, 0.6, 0],  ... %[-1, 0.4, 1, 0.6, 0], ... %
    'L2',                           1, ...
    'swap',                         1 ...
    );
```

Do you have any idea to improve this performance ?

Best regards,

**Comment by Robert0812** [comment]
I didn't test it on linux, and I don't think cross-platform evaluation will deteriorate the performance. Keep the original parameters, and make sure your modification on dense feature computation doesn't change the feature values computed. And also make sure you follow the readme instructions exactly.

**Comment by jrabary** [comment]
Thanks for your answer. Do you have an example of a dense feature computed with your version on your platform so I can unit test this part of the code.

**Comment by Robert0812** [comment]
You can find an example of extracted dense feature in the repository https://github.com/Robert0812/dense_feat

**Comment by jrabary** [comment]
Thanks. There was some error in the feature computation due to the rgb2lab conversion. But, I still don't get the performance in the readme outof the box (even with matlab).

**Comment by Robert0812** [comment]
You can try it on Windows. Many feedbacks validate that the performance can be obtained with Matlab on Windows. There must be some computational difference in cross platform testing, but I don't have time to exam in detail recently.

**Comment by huozhonghua** [comment]
Hi,
Recently,I'm reading your paper and trying to running your code of salience_reid.As your paper says adjacency constrained search was used to accomplish patch matching ,but your code  in the link https://github.com/Robert0812/salience_reid/blob/master/code/mutualmap.m doesn't reflect this,isn't it ?

**Comment by zengguodong** [comment]
Hi,

That is not my work, I just folk it on my Github. And the author page is  http://www.ee.cuhk.edu.hk/~rzhao/‍
, and you could email him.

best regrads.

---

---

曾国栋
北京航空航天大学 计算机学院 数字媒体实验室
Tel: +86-156－5292－6453 
Email:1055414730@qq.com

------------------ Original ------------------

**Comment by Robert0812** [comment]
> As your paper says adjacency constrained search was used to accomplish patch matching ,but your code in the link https://github.com/Robert0812/salience_reid/blob/master/code/mutualmap.m doesn't reflect this,isn't it ?

Hi, guys, 

Yes, the released version doesn't include the adjacency search but still gives comparable results. Because pedestrian images like in VIPeR dataset are manually cropped and well aligned, so we just save the adjacency search in this demo code for better efficiency without sacrificing performance. But you can easily add the adjacency search in [mutual_map.m](https://github.com/Robert0812/salience_reid/blob/master/code/mutualmap.m), and will get  performance gain in the case that pedestrian images are not manually obtained.
