### ISSUE TITLE
Encountering issue while trying to run demo_salience_reid_viper

### ISSUE THREAD

**Issue by arkobarman** [Robert0812/salience_reid#3]
I am getting the following error when I type demo_salience_reid_viper(10):

Error using mat2cell (line 106)
Input arguments, D1 through D2, must sum to each dimension of the input
matrix size, [0  0].'

Error in initialcontext_general (line 17)
cell_all = mat2cell(array_all, ones(1, length(fnames)), [4, 3, 4]);

Error in demo_salience_reid_viper (line 66)
initialcontext_general;

**Comment by Robert0812** [comment]
The error shows that matrix "array_all" is of zero size, which means your input image files are not correctly loaded. Check you dataset whether it is put in the correct directory.

**Comment by arkobarman** [comment]
Thanks for the reply. I could do it but it takes a lot of time due to the use of parpool, specially for ETHZ. Is there a version of this code without using parpool or parfor?

**Comment by Robert0812** [comment]
No, but you can comment the line "matlabpool" or directly revise "parfor" to "for" to disable the usage of parpool

**Comment by arkobarman** [comment]
Thanks. I could get it to run now.
