### ISSUE TITLE
demo_salience_reid_ethz

### ISSUE THREAD

**Issue by phupv93** [Robert0812/salience_reid#4]
Dear Rober0812,
I have joined in person re-identification field for a month. And now,  I am studying about your algorithms to solve saliency problem. The program with dataset Viper run well. But with dataset Ethz, I have a trouble in "combine with other features and evaluation" step. I do not know how "disty.mat", "color.mat", "hist.mat", "epitext.mat" are generated. Could you show me the way to create or use these matrix.
Best Regards, 
Phu Pham

**Comment by Robert0812** [comment]
These are distances produced by [SDALF](https://github.com/lorisbaz/SDALF)

**Comment by phupv93** [comment]
Thanks for your help.

**Comment by thuybinh** [comment]
Dear Robert0812, 
Could you tell me what "posemask_viper.mat" is and how to generate this matrix?
Best Regards,
Binh Nguyen

**Comment by Feesics** [comment]
I met the similar problem as you described, have you solved that problem? I hope you can tell me the solution detaily about this problem, thanks a lot.
