### ISSUE TITLE
Posemask_viper

### ISSUE THREAD

**Issue by thuybinh** [Robert0812/salience_reid#5]
Dear Robert, 
I have been working with your source code. Could you tell me what "posemask_viper.mat" is and how to generate this matrix. 
Best Regards, 
ThuyBinh

**Comment by Robert0812** [comment]
We use [pose estimation](http://www.ics.uci.edu/~yyang8/research/pose/index.html) approach to generate pose skeleton, and apply Gaussian blur to estimated joints, that produces posemask_viper.mat.

**Comment by thuybinh** [comment]
Thanks for your help!
Best Regards,
ThuyBinh
